FROM php:7.3-apache

ARG DEV_USER_UID=1000

RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get autoremove -y
RUN apt-get install -y --no-install-recommends \
    curl \
    git \
    nano \
    openssh-client \
    screen \
    sudo \
    unzip \
    wget
RUN rm -r /var/lib/apt/lists/*

RUN /usr/sbin/update-ca-certificates

RUN pecl channel-update pecl.php.net

RUN apt-get install -y --no-install-recommends \
    libfreetype6-dev \
    libjpeg-dev \
    libpng-dev \
    libtiff-dev \
    libwebp-dev \
    libxpm-dev

RUN docker-php-ext-configure gd --with-freetype-dir --with-jpeg-dir --with-png-dir --with-zlib-dir --with-webp-dir --with-xpm-dir --with-gd
RUN docker-php-ext-install -j$(nproc) gd

#    libicu-dev \
#    libpq-dev \

#RUN docker-php-ext-install -j$(nproc) bcmath
#RUN docker-php-ext-install -j$(nproc) intl
#RUN docker-php-ext-install -j$(nproc) mysqli
#RUN docker-php-ext-install -j$(nproc) opcache
#RUN docker-php-ext-install -j$(nproc) pcntl
#RUN docker-php-ext-install -j$(nproc) pdo_mysql
#RUN docker-php-ext-install -j$(nproc) pdo_pgsql
#RUN docker-php-ext-install -j$(nproc) soap
#RUN docker-php-ext-install -j$(nproc) sockets

#    libxslt-dev \
#RUN docker-php-ext-install -j$(nproc) xslt

#    libzip-dev \
#RUN docker-php-ext-install -j$(nproc) zip

#RUN pecl install ast
#RUN docker-php-ext-enable ast

#    libmcrypt-dev \
#RUN pecl install mcrypt-1.0.2
#RUN docker-php-ext-enable mcrypt

#    libmemcached-dev \
#RUN pecl install memcached
#RUN docker-php-ext-enable memcached

#RUN pecl install mongodb
#RUN docker-php-ext-enable mongodb

#RUN pecl install redis
#RUN docker-php-ext-enable redis

#RUN pecl install xdebug

ADD rootfs /

RUN bash /docker-build/00-user.sh
RUN bash /docker-build/10-bash.sh
RUN bash /docker-build/20-apache.sh

RUN bash /docker-build/50-composer.sh
RUN bash /docker-build/60-symfony.sh
RUN bash /docker-build/70-phpunit.sh 7

USER dev

VOLUME /www
WORKDIR /www

EXPOSE 80
CMD ["sudo", "apache2-foreground"]
