FROM php:5.6-apache

ARG DEV_USER_UID=1000
ENV TERM=xterm-256color

RUN apt-get update && \
    apt-get upgrade -y && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    cron \
    curl \
    git \
    htop \
    jq \
    nano \
    openssh-client \
    screen \
    ssl-cert \
    sudo \
    unzip \
    wget

RUN /usr/sbin/update-ca-certificates

ADD rootfs /

RUN (bash /setup/00-user.sh)
RUN (bash /setup/10-bash.sh)
RUN (bash /setup/20-apache.sh)
RUN (bash /setup/30-php.sh \
        bcmath-stable \
        gd-stable \
        intl-stable \
        mcrypt-stable \
        pcntl-stable \
        pdo_mysql-stable \
        pdo_pgsql-stable \
        xdebug-^2.5 \
        zip-stable \
    )
RUN (bash /setup/50-composer.sh)
RUN (bash /setup/60-symfony.sh)
RUN (bash /setup/70-phpunit.sh 4 5)
RUN (bash /setup/90-utils.sh)

RUN rm -rf /setup/ /var/lib/apt/lists/*

ADD config/xdebug2.ini /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

USER dev

VOLUME /www
WORKDIR /www

EXPOSE 80
EXPOSE 443

CMD ["sudo", "apache2-foreground"]
