FROM php:8.2-apache

ARG DEV_USER_UID=1000
ENV TERM=xterm-256color

RUN apt-get update && \
    apt-get upgrade -y && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    cron \
    curl \
    git \
    htop \
    nano \
    openssh-client \
    screen \
    ssl-cert \
    sudo \
    unzip \
    wget

RUN /usr/sbin/update-ca-certificates

ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/
RUN chmod +x /usr/local/bin/install-php-extensions && sync && install-php-extensions \
 bcmath-stable \
 gd-stable \
 intl-stable \
 mcrypt-stable \
 pcntl-stable \
# xdebug-^3.2 \
 zip-stable

RUN install-php-extensions xdebug/xdebug@3.2.0

ADD rootfs /

RUN (bash /setup/00-user.sh) && \
    (bash /setup/10-bash.sh) && \
    (bash /setup/20-apache.sh) && \
    (bash /setup/50-composer.sh) && \
    (bash /setup/60-symfony-cli.sh) && \
    (bash /setup/70-phpunit.sh 8 9) && \
    (bash /setup/90-utils.sh) && \
    (rm -fr /setup/)

RUN rm -rf /var/lib/apt/lists/*

USER dev

VOLUME /www
WORKDIR /www

EXPOSE 80
EXPOSE 443

CMD ["sudo", "apache2-foreground"]
