FROM php:7.3-apache

ARG DEV_USER_UID=1000
ENV TERM=xterm-256color

RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y --no-install-recommends \
    curl \
    git \
    htop \
    nano \
    openssh-client \
    screen \
    sudo \
    unzip \
    wget

RUN /usr/sbin/update-ca-certificates

ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/
RUN chmod +x /usr/local/bin/install-php-extensions

RUN install-php-extensions \
 apcu \
 ast \
 bcmath \
 exif \
 gd \
 intl \
 mbstring \
 mcrypt \
 memcached \
 mongodb \
 mysqli \
 opcache \
 pcntl \
 pdo_firebird \
 pdo_mysql \
 pdo_odbc \
 pdo_pgsql \
 redis \
 soap \
 sockets \
 tidy \
 uuid \
 xdebug \
 xsl \
 yaml \
 zip

ADD rootfs /

RUN rm /usr/local/etc/php/conf.d/xdebug2.ini
RUN rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

RUN bash /docker-build/00-user.sh
RUN bash /docker-build/10-bash.sh
RUN bash /docker-build/20-apache.sh
RUN bash /docker-build/50-composer.sh
RUN bash /docker-build/60-symfony.sh
RUN bash /docker-build/70-phpunit.sh 7 8 9

USER dev

RUN bash /docker-build/composer-global.sh 'laravel/installer'

VOLUME /www
WORKDIR /www

EXPOSE 80
CMD ["sudo", "apache2-foreground"]
