FROM php:7.1-apache

ARG DEV_USER_UID=1000

RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y --no-install-recommends \
    curl \
    git \
    nano \
    openssh-client \
    screen \
    sudo \
    unzip \
    wget

RUN /usr/sbin/update-ca-certificates

RUN pecl channel-update pecl.php.net

RUN pecl install ast \
    && docker-php-ext-enable ast

RUN docker-php-ext-install -j$(nproc) bcmath

RUN apt-get install -y --no-install-recommends \
        libfreetype6-dev \
        libjpeg-dev \
        libpng-dev \
        libtiff-dev \
        libwebp-dev \
        libxpm-dev \
    && docker-php-ext-configure gd \
        --with-freetype-dir \
        --with-jpeg-dir \
        --with-png-dir \
        --with-zlib-dir \
        --with-webp-dir \
        --with-xpm-dir \
        --with-gd \
    && docker-php-ext-install -j$(nproc) gd

RUN apt-get install -y --no-install-recommends libicu-dev \
    && docker-php-ext-install -j$(nproc) intl

RUN apt-get install -y --no-install-recommends libmcrypt-dev \
    && pecl install mcrypt-1.0.0 \
    && docker-php-ext-enable mcrypt

RUN apt-get install -y --no-install-recommends libmemcached-dev \
    && pecl install memcached \
    && docker-php-ext-enable memcached

RUN pecl install mongodb \
    && docker-php-ext-enable mongodb

RUN docker-php-ext-install -j$(nproc) mysqli

RUN docker-php-ext-install -j$(nproc) opcache

RUN docker-php-ext-install -j$(nproc) pcntl

RUN docker-php-ext-install -j$(nproc) pdo_mysql

RUN apt-get install -y --no-install-recommends libpq-dev \
    && docker-php-ext-install -j$(nproc) pdo_pgsql

RUN pecl install redis \
    && docker-php-ext-enable redis

RUN apt-get install -y --no-install-recommends libxml2-dev \
    && docker-php-ext-install -j$(nproc) soap

RUN docker-php-ext-install -j$(nproc) sockets

RUN apt-get install -y --no-install-recommends libxslt-dev \
    && docker-php-ext-install -j$(nproc) xsl

RUN apt-get install -y --no-install-recommends libzip-dev \
    && docker-php-ext-install -j$(nproc) zip

RUN pecl install xdebug

ADD rootfs /

RUN bash /docker-build/00-user.sh
RUN bash /docker-build/10-bash.sh
RUN bash /docker-build/20-apache.sh
RUN bash /docker-build/50-composer.sh
RUN bash /docker-build/60-symfony.sh
RUN bash /docker-build/70-phpunit.sh 5 6 7

RUN apt-get autoremove -y
RUN apt-get autoclean -y
RUN rm -r /var/lib/apt/lists/*

USER dev

VOLUME /www
WORKDIR /www

EXPOSE 80
CMD ["sudo", "apache2-foreground"]
