FROM php:5.6-apache

ARG DEV_USER_UID=1000
ENV TERM=xterm-256color

RUN apt-get update
RUN apt-get upgrade -y
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    cron \
    curl \
    git \
    htop \
    nano \
    openssh-client \
    screen \
    ssl-cert \
    sudo \
    unzip \
    wget

RUN /usr/sbin/update-ca-certificates

ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/
RUN chmod +x /usr/local/bin/install-php-extensions && sync && install-php-extensions \
 amqp \
 apcu \
 bcmath \
 bz2 \
 exif \
 gd \
 intl \
 mbstring \
 mcrypt \
 memcached \
 mongodb \
 mysqli \
 oauth \
 opcache \
 pcntl \
 pdo_firebird \
 pdo_mysql \
 pdo_odbc \
 pdo_pgsql \
 redis \
 soap \
 sockets \
 tidy \
 uuid \
 xdebug \
 xsl \
 yaml \
 zip

ADD rootfs /

ADD config/xdebug2.ini /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

RUN (bash /docker-build/00-user.sh) && \
    (bash /docker-build/10-bash.sh) && \
    (bash /docker-build/20-apache.sh) && \
    (bash /docker-build/50-composer.sh) && \
    (bash /docker-build/70-phpunit.sh 4 5) && \
    (bash /docker-build/90-utils.sh)

USER dev

RUN bash /docker-build/composer-global.sh 'laravel/installer'

VOLUME /www
WORKDIR /www

EXPOSE 80
EXPOSE 443

CMD ["sudo", "apache2-foreground"]

RUN bash /docker-build/99-summary.sh

